management:
  endpoints:
    web:
      exposure:
        include: prometheus

spring:
  kafka:
    template:
      default-topic: notificationTopic
    consumer:
      group-id: notificationId
      properties:
        spring:
          json:
            type:
              mapping: event:com.programming.techie.OrderPlacedEvent
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    bootstrap-servers: localhost:9092
  application:
    name: notification-service
server:
  port: '0'
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
